# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cba24c429240547a9670403c7494747fcd5e6ecdbd56485369ed463ae438db11719db31d5b92a4617ed92733e670142b635a2c96e251c92d8f8b94f8badcfbdd

test:
  secret_key_base: cb1b56028539967fe808627627d1a8aaf87762b68ac0588ecc416dcf72e48fde5130afbd1577ef88c127aadc4a0db633374420e37f7ade28ed76261b85714c01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
